services:
  - type: web
    name: kahe-cms-all-in-one
    runtime: python
    buildCommand: |
      cd frontend && npm install && CI=false npm run build
      cd ../backend && pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kahe-cms-db-final
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: REACT_APP_API_URL
        value: "" # Empty means it will use relative path in frontend

databases:
  - name: kahe-cms-db-final
    plan: free
