services:
  - type: web
    name: kahe-cms
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir backend/cms_project cms_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NODE_VERSION
        value: 22.13.1
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend/cms_project"
      - key: DATABASE_URL
        sync: false
