# Generated by Django 6.0.6 on 2026-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='allotted_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='mne',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_hours',
            field=models.IntegerField(default=0),
        ),
    ]
